#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

#Variables
die() ## PHP function copy
{
	echo "$@"
	exit
}
[ "$(uname -s)" = "Darwin" ] || die "This script must be run on a Darwin system"

if [ "$1" == "--version" ]
then
	cd "$(dirname "$0")"
	version="$(cat python/lib/Variables.py | grep 'os.environ\["VERSION"\] = ' | cut -d = -f2 | tr -d \" | tr -d " ")"
	die "PlayOnMac $version"
fi

export PYTHON="python"
export POL_OS="Mac"

[ "$PLAYONLINUX" = "" ] || die "You are already in a PlayOnMac environment"

if [ ! "$(which $PYTHON)" ]
then
	echo "Please install $PYTHON before trying to run PlayOnMac"
fi

cd "$(dirname "$0")/../../MacOS" || die "Unable to find Mac OS PlayOnMac .app environment"
./playonmac
exit $?
