#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

#Variables
die() ## PHP function copy
{
	echo "$@"
	exit
}
[ "$(uname -s)" = "Linux" ] || die "This script must be run on a linux system"

export PYTHON="python"
export POL_OS="Linux"
export UBUNTU_MENUPROXY=0 

[ "$PLAYONLINUX" = "" ] || die "You are already in a PlayOnLinux environement" 

if [ ! "$(which $PYTHON)" ]
then
	echo "Please install $PYTHON before trying to run PlayOnLinux"
fi

if [ "$1" == "--run" ]
then
	shift
	NAME="$1"
	shift
	./playonlinux-bash "$HOME/.PlayOnLinux/shortcuts/$NAME" "$@"
else
	cd "$(dirname "$0")/python"
	"$PYTHON" mainwindow.py "$@"
fi
exit $?
