#!/usr/bin/env bash

# Copyright (C) 2007-2011 Pâris Quentin
# Copyright (C) 2007-2010 PlayOnLinux Team

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

[ "$(uname -s)" = "Darwin" ] && export POL_OS="Mac"
[ "$(uname -s)" = "Linux" ] && export POL_OS="Linux"
[ "$(uname -s)" = "FreeBSD" ] && export POL_OS="FreeBSD"

export SILENT="TRUE"

if [ "$PLAYONLINUX" = "" ]
then
	export WorkingDirectory="$PWD"
	CURDIR=`dirname "$0"`
	cd "$CURDIR"
	CURDIR="$(pwd)"
	export MACHTYPE
	cd "$WorkingDirectory"
	exec python3 "$CURDIR/python/wrapper.py" "$CURDIR/bash/$(basename "$0")" "$@"
else
	exec bash "$PLAYONLINUX/bash/$(basename "$0")" "$@"
fi
