#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

if [ "$POL_OS" = "Mac" ]; then
   cat << EOF > /tmp/playOnMacOpenTerminal
#!/bin/bash
export PLAYONLINUX="$PLAYONLINUX"
source "\$PLAYONLINUX/lib/sources"
$(export)

"\$PLAYONLINUX/bash/polshell"
EOF
   chmod +x /tmp/playOnMacOpenTerminal
   open -b com.apple.terminal /tmp/playOnMacOpenTerminal
   exit 0
fi

[ "$DEBIAN_PACKAGE" = "FALSE" ] && TITLEADD="-T $APPLICATION_TITLE"
"$POL_TERM" $TITLEADD -e "$PLAYONLINUX/bash/polshell"
