.TH PLAYONLINUX-DAEMON 1 "February  6, 2009"

.SH NAME
playonlinux-daemon \- daemon to handle disk insertion in PlayOnLinux

.SH SYNOPSIS
.B playonlinux-daemon
.RI [ options ]

.SH DESCRIPTION
.B playonlinux-daemon
is a daemon to handle disk insertion within PlayOnLinux. It still needs testing and may not work flawlessly.
.br
Users who want to handle autoruns with PlayOnLinux should launch this script at startup.

.SH OPTIONS
.TP
.I "--version"
 Show version number and exit.
.TP
.I "--kill"
 Kill the daemon.

.SH AUTHOR
playonlinux was written by Quentin Pâris <qparis@playonlinux.com>.
.PP
This manual page was written by Bertrand Marc <beberking@gmail.com>,
for the Debian project (but may be used by others).
