#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 
if [ ! "$INCLUDED" ]
then
	INCLUDED="1" # On évite l'inclusion en boucle
	source "$PLAYONLINUX/lib/variables"
	source "$PLAYONLINUX/lib/check_depend"
	source "$PLAYONLINUX/lib/applications"
	source "$PLAYONLINUX/lib/main"
	source "$PLAYONLINUX/lib/interface_v3"
	source "$PLAYONLINUX/lib/wine"
	source "$PLAYONLINUX/lib/plugins"
	source "$PLAYONLINUX/lib/pol_debug"
fi
