#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# This is the startup script

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 

# This script tests OpenGL libs
# Usage :

# check_gl [arch]
# Arch = (x86 | amd64)

if [ "$1" = "x86" ]
then
	ld -lGL -lGLU -m elf_i386 2> /dev/null
	if [ "$?" = "0" ]
	then
		echo "32 bits OpenGL is supported by your system"
		exit 0
	else
		echo "32 bits OpenGL is not supported by your system"
		exit 1
	fi
fi
if [ "$1" = "amd64" ]
then
	ld -lGL -lGLU -m elf_x86_64 2> /dev/null
	if [ "$?" = "0" ]
	then
		echo "64 bits OpenGL is supported by your system"
		exit 0
	else
		echo "64 bits OpenGL is not supported by your system"
		exit 1
	fi
fi