#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

WorkingDirectory="$PWD"
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

app="$1"
doc="$2"
shift 2

if [ ! -e "$POL_USER_ROOT/shortcuts/$app" ]; then
	POL_SimpleMessage "$app is not installed." 
	echo "$app is not installed."
	exit
fi

if [ "$doc" ]; then
	POL_Debug_Message "App to run: $app"
	POL_Debug_Message "File to run: $doc"

	if [ "${doc::1}" != "/" ]; then
		doc="$WorkingDirectory/$doc"
	fi
	pref="$(POL_Shortcut_GetPrefix "$app")"
	POL_Wine_SelectPrefix "$pref"	
	realpath="$(POL_Wine winepath -w "$doc")"
fi
exec bash "$POL_USER_ROOT/shortcuts/$app" "$realpath" "$@"
