#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
	exit 0
fi

source "$PLAYONLINUX/lib/sources" 

POL_SetupWindow_Init
version=$1
POL_SetupWindow_free_presentation "Wine $1" "$(eval_gettext "This wizard will help you to install Wine: ")$version $(eval_gettext "on the PlayOnLinux environment.")"
rm -f "$REPERTOIRE/WineVersions/failed" "$REPERTOIRE/WineVersions/installed"
POL_SetupWindow_install_wine "$1"
if [ -e "$REPERTOIRE/WineVersions/installed" ] ; then
	POL_SetupWindow_message "$(eval_gettext 'Wine has been installed successfully.')" "Wine $1"
else
	POL_SetupWindow_message "$(eval_gettext 'Failed to install Wine.')" "Wine $1"
fi
POL_SetupWindow_Close
