#!/bin/bash

# Copyright (C) 2007-2013 PlayOnLinux Team
# Copyright (C) 2007-2013 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# Install wine-mono

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="$(eval_gettext '$APPLICATION_TITLE Mono installer')"
POL_SetupWindow_Init
[ "$POL_OS" = "Linux" ] && wos="linux"
[ "$POL_OS" = "Mac" ] && wos="darwin"

cd "$POL_USER_ROOT/wine/$wos-x86" || exit 1
for file in *; do
	[ -d "$POL_USER_ROOT/wine/$wos-x86/$file" ] && POL_Wine_Install_resources mono "$file"
done

cd "$POL_USER_ROOT/wine/$wos-amd64" || exit 1
for file in *; do
	[ -d "$POL_USER_ROOT/wine/$wos-amd64/$file" ] && POL_Wine_Install_resources mono "$file" "amd64"
done
POL_SetupWindow_Close
