#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 

menu="$1"
if [ "$menu" = "ExecLiveInstall" ]
then
	bash "$PLAYONLINUX/bash/manual_install"
	exit
fi

if [ ! "$menu" = "" ]
then
	export TITLE="$menu"
	type="$(echo $menu | cut -d ':' -f1)"
	if [ "$type" = "get" ]
	then
		id=$(echo "$menu" | cut -d ":" -f2)
		rm "$REPERTOIRE/install"
		wget "$SITE/V4_data/repository/get_file_n.php?version=PlayOn$POL_OS-$VERSION&id=$id" -O "$REPERTOIRE/install" -q
		[ -e "$REPERTOIRE/install" ] && POL_Bash "$REPERTOIRE/install"
		exit
	fi
	menu=${menu//" "/"%20"}
	rm "$REPERTOIRE/install"
	wget "$SITE/V4_data/repository/get_file.php?version=playonlinux-$VERSION&id=$menu" -O "$REPERTOIRE/install" -q
	[ -e "$REPERTOIRE/install" ] && POL_Bash "$REPERTOIRE/install"
fi

