#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 


cd "$POL_USER_ROOT/wineprefix"
POL_SetupWindow_Init
POL_SetupWindow_question "$(eval_gettext 'Are you sure you want to shutdown all active $APPLICATION_TITLE applications?')" "$APPLICATION_TITLE"
if [ "$APP_ANSWER" = "TRUE" ]
then
	POL_SetupWindow_wait_next_signal  "$(eval_gettext 'Please wait...')" "$APPLICATION_TITLE"
	for prefix in *
	do
		export WINEPREFIX="$POL_USER_ROOT/wineprefix/$prefix"
                (POL_Wine_AutoSetVersionEnv
		wineserver -k)
		POL_Debug_Message "Killed $prefix"
	done
fi
POL_SetupWindow_Close
