#!/usr/bin/env bash

# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# This script makes shortcut of programs

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 


TITLE="$(eval_gettext '$APPLICATION_TITLE shortcut creator')"

if [ "$1" ]; then
	PACKAGE="$1"
else
	POL_SetupWindow_games "$(eval_gettext "Please choose a software to package")" "$TITLE"
	PACKAGE="$APP_ANSWER"
fi

POL_SetupWindow_Init
POL_SetupWindow_wait_next_signal "$(eval_gettext "Creating shortcut...")" "$TITLE"
POL_Shortcut_MakeDesktopShortcut "$PACKAGE"
POL_SetupWindow_message "$(eval_gettext "The shortcut has been placed on your desktop")" "$TITLE"
POL_SetupWindow_Close



exit 0
# Standalone package code. Deprecated
if [ "$KIND_OF_PACKAGE" = "1" ]
then
	prefix="$(detect_wineprefix "$PACKAGE")"
	wversion="$(detect_wineversion "$PACKAGE")"
	


	echo $prefix
	make_skeleton "$PACKAGE" 
	make_icon "$PACKAGE"
	make_standalone_script "$PACKAGE" "$prefix"
	make_plist "$PACKAGE" "$shortname"
	
	POL_SetupWindow_wait_next_signal "$(eval_gettext "Copying virtual drive")" "$TITLE"
	cp -R -p "$prefix" "$DIRAPP/Contents/Resources/virtual_drive"
	sleep 2
	if [ ! -e "$POL_USER_ROOT/WineVersions/$wversion/" ]
	then
		wversion=""
	fi
	POL_SetupWindow_wait_next_signal "Including wine" "$TITLE"
	if [ "$wversion" = "" ]
	then
		cp -R -p "$PLAYONLINUX/../unix/wine" "$DIRAPP/Contents/Resources/wine"
	else
		cp -R -p "$POL_USER_ROOT/WineVersions/$wversion/" "$DIRAPP/Contents/Resources/wine"
	fi
	cp "$PLAYONLINUX"/../unix/tools/lib/* "$DIRAPP/Contents/Resources/wine/lib/"
	
fi
