#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# PlayOnLinux / PlayOnMac Online

[ "$PLAYONLINUX" = "" ] && exit 
source "$PLAYONLINUX/lib/sources"

TITLE="$APPLICATION_TITLE Online"

personal_scripts()
{
	POL_Website_GET "$SITE/V3_data/repository/get_personal_list.php"
	POL_SetupWindow_menu "$(eval_gettext "This is the list of the scripts you sent to us. You can run one of them")" "$TITLE" "$(POL_Website_Result)" "~"
	POL_Website_GET "$SITE/V3_data/repository/get_file.php?id=$APP_ANSWER"
	POL_Website_Result > "$POL_USER_ROOT/install"
	cd "$POL_USER_ROOT"
	POL_SetupWindow_wait "$(eval_gettext "Running...")" "$TITLE"
	POL_Bash "install" 
}
main_menu()
{
	LNG_SCRIPTS="$(eval_gettext "Run one of your personal scripts")"
	LNG_LOGOUT="$(eval_gettext "Logout")"
	POL_SetupWindow_menu_num "$(eval_gettext 'You are connected to $APPLICATION_TITLE online')" "$TITLE" "$LNG_SCRIPTS~$LNG_LOGOUT" "~"
	ACTION="$APP_ANSWER"
	if [ "$ACTION" = "0" ]
	then
		personal_scripts
	fi
	if [ "$ACTION" = "1" ]
	then
		POL_Website_Close
		POL_Website_logout
		POL_SetupWindow_message "$(eval_gettext 'You have been successfully logged out of $APPLICATION_TITLE Online\nYou can safely close this window')" "$TITLE"
		POL_SetupWindow_Close
	fi
	main_menu
}
POL_SetupWindow_Init
POL_Website_login
POL_Website_Init
main_menu

exit 0