#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# URL handler

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"


STRING="$1"
STRING="${STRING/playonlinux:\/\//http://}"
STRING="${STRING/playonmac:\/\//http://}"

url_cut="$(echo $STRING | cut -d "/" -f3)" 
if [ "$url_cut" == "www.playonlinux.com" ] || [ "$url_cut" == "www.playonmac.com" ]
then
	$POL_WGET "$STRING" -O- > "$POL_USER_ROOT/install"
	POL_Bash "$POL_USER_ROOT/install"
fi
