#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2008 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# Allow to call a POL Bash statement from Python

# Usage POL_Command (--init) (--prefix [PrefixName]|[Shortcut Name]) [Command]
# Example POL_Command "Internet Explorer 6" Set_OS winxp

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

[ "$1" == "--init" ] && INIT="TRUE" && shift

[ "$INIT" = "TRUE" ] && POL_SetupWindow_Init

if [ "$1" = "--prefix" ]
then
	shift
	export PREFIXNAME="$1"
	export WINEPREFIX="$POL_USER_ROOT/wineprefix/$1"
else
	export WINEPREFIX="$(detect_wineprefix "$1")"
fi
export TITLE="$1"
shift
#[ "$WINEVERSION" = "" ] || Use_WineVersion $WINEVERSION
"$@"

[ "$INIT" = "TRUE" ] && POL_SetupWindow_Close
exit
