#!/bin/bash

# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# This script is called when POL/POM runs a program.
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"


TITLE="$APPLICATION_TITLE"


if [ "$1" ]
then
PACKAGE="$1"
else
POL_SetupWindow_Init
POL_SetupWindow_games "$(eval_gettext "Please choose a software to run")" "$TITLE"
PACKAGE="$APP_ANSWER"
POL_SetupWindow_Close
fi

cd "$REPERTOIRE/shortcuts"

export POL_IgnoreWineErrors="True"

$(POL_Config_Read PRE_RUNNING)
if [ -e "$POL_USER_ROOT/configurations/pre_shortcut/$PACKAGE" ]; then
	source "$POL_USER_ROOT/configurations/pre_shortcut/$PACKAGE"
fi
shift
# export FORCE_OSX_DOCK="TRUE"
export COMMON_NAME="$PACKAGE"

bash "$PACKAGE" "$@"

if [ ! "$?" = "0" ]
then 


	POL_SetupWindow_Init
	POL_SetupWindow_wait_next_signal "$(eval_gettext '$APPLICATION_TITLE debugger is starting...')" "$TITLE"
	if [ ! "$(cat "$PACKAGE" | grep 'export WINEDEBUG="-all"')" = "" ]
	then
		POL_SetupWindow_message "$(eval_gettext '$PACKAGE crashed.\n\nYou need to enable debugging to get more details.\nPlease go to configure menu')" "$TITLE"
	else
		POL_SetupWindow_message "$(eval_gettext '$PACKAGE crashed.')" "$TITLE"
	fi
	POL_SetupWindow_Close
fi
$(POL_Config_Read POST_RUNNING)
