#!/bin/bash
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
export WINEPREFIX="/Users/tinou/Library/PlayOnMac//wineprefix/InternetExplorer6"
export WINEDEBUG="-all"
#POL_Log=Internet Explorer 6
#ScriptID=Internet Explorer 6
cd "/Users/tinou/Library/PlayOnMac//wineprefix/InternetExplorer6/drive_c/.//Program Files/Internet Explorer"
POL_Wine "IEXPLORE.EXE"  "$@"

