#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# This is the startup script

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 

POL_Debug_Message "$APPLICATION_TITLE ($VERSION) is starting"


# POL / POM won't work without that 
build_user_state_directory

# Cleaning tmp directory
clean_tmp

# Mac OS Catalina: Remove legacy wine versions
if [[ "$OSX_VERSION" -ge 19 ]]; then
    if [[ ! -e "$POL_USER_ROOT/wine/darwin-x86-legacy" ]]; then
        [[ -e "$POL_USER_ROOT/wine/darwin-x86" ]] && mv "$POL_USER_ROOT/wine/darwin-x86" "$POL_USER_ROOT/wine/darwin-x86-legacy"
        mkdir -p "$POL_USER_ROOT/wine/darwin-x86-legacy"
    fi
fi

### Operations below are background asynchronous tasks

(
# Run XQuartz

if [ "$(POL_Config_Read VDRIVES_LINK_MADE)" = "" ]; then
	POL_Config_Write VDRIVES_LINK_MADE TRUE
	[ -e "$HOME/$APPLICATION_TITLE's virtual drives" ] || ln -s "$POL_USER_ROOT/wineprefix/" "$HOME/$APPLICATION_TITLE's virtual drives"
fi

) &
