#!/usr/bin/env bash

# Copyright (C) 2007-2011 PlayOnLinux Team
# Copyright (C) 2007-2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Uninstall a program

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

INTERACTIVE=1
if [ "$1" = "--non-interactive" ]; then
	unset INTERACTIVE
	shift
fi

TITLE="$(eval_gettext '$APPLICATION_TITLE Uninstaller')"
[ -n "$INTERACTIVE" ] && POL_SetupWindow_Init "$PLAYONLINUX/resources/images/setups/delete/top.png" "$PLAYONLINUX/resources/images/setups/delete/left.jpg"

if [ "$1" = "" ]; then
	if [ -z "$INTERACTIVE" ]; then
		echo "Syntax: $0 [--non-interactive] \"Shortcut name\"" >&2
		exit 1
	fi
	POL_SetupWindow_shortcuts_list "$(eval_gettext 'Please select a program to uninstall')" "$TITLE"
	ProgramUninstall="$APP_ANSWER"
else
	ProgramUninstall="$1"
fi

APP_NAME="$POL_USER_ROOT/shortcuts/$ProgramUninstall"
if [ -e "$APP_NAME" ]
then
	application_prefixe=$(detect_wineprefix "$ProgramUninstall")
	delete_var=$ProgramUninstall
	[ -n "$INTERACTIVE" ] && POL_SetupWindow_free_presentation "$TITLE" "$(eval_gettext "This wizard will help you to uninstall: ")$delete_var\n$(eval_gettext "Click Next to continue.")"

	# Icones
	rm -f "$POL_USER_ROOT/icones/32/$ProgramUninstall"
	rm -f "$POL_USER_ROOT/icones/full_size/$ProgramUninstall"
	rm -f "$POL_USER_ROOT/configurations/reports/$ProgramUninstall" 2> /dev/null
	rm -f "$POL_USER_ROOT/configurations/links/$ProgramUninstall" 2> /dev/null

	# Shortcut
	rm -f "$POL_USER_ROOT/shortcuts/$ProgramUninstall"
	rm -f "$HOME/.local/share/applications/playonlinux-$ProgramUninstall.desktop"
	rm -f "$DESKTOP/$ProgramUninstall.desktop"

	# Note: only interactive mode checks if the prefix should be removed
	if [ -n "$INTERACTIVE" ]; then
		POL_SetupWindow_wait "$(eval_gettext 'Uninstalling...')" "$(eval_gettext '$APPLICATION_TITLE Uninstaller')" 
		sleep 1
		clean_wineprefix $application_prefixe
		POL_SetupWindow_message "$delete_var$(eval_gettext ' has been uninstalled successfully.')" "$(eval_gettext '$APPLICATION_TITLE Uninstaller')"
	fi
else
	if [ -z "$INTERACTIVE" ]; then
		echo "Error, shortcut $ProgramUninstall not found" >&2
		exit 2
	fi
	POL_SetupWindow_message "$(eval_gettext "Cannot find the shortcut")" "$(eval_gettext '$APPLICATION_TITLE Uninstaller')"
fi
[ -n "$INTERACTIVE" ] && POL_SetupWindow_Close
