#!/usr/bin/env bash

# Copyright (C) 2007-2011 PlayOnLinux Team
# Copyright (C) 2007-2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# Upgrade PlayOnLinux using git

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="$(eval_gettext '$APPLICATION_TITLE auto-updater')"
POL_SetupWindow_Init
POL_SetupWindow_wait "$(eval_gettext 'Updating $APPLICATION_TITLE from GIT...')" "$TITLE"
cd "$PLAYONLINUX"
git remote update
if LC_ALL=C git status |grep -q 'Your branch is behind'; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to update and restart $APPLICATION_TITLE?')" "$TITLE"
    if [ "$APP_ANSWER" = "TRUE" ]; then
        git pull
        POL_Restart
    fi
else
    POL_SetupWindow_message "$(eval_gettext 'Already up-to-date.')" "$TITLE"
fi

POL_SetupWindow_Close
