#!/usr/bin/env bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2008 Pâris Quentin
# Copyright (C) 2009 Łukasz Wojniłowicz

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

# Used by Configuration window for running Wine setup commands 

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

POL_SetupWindow_Init
POL_SetupWindow_wait_next_signal "$(eval_gettext "Please wait...")" "$(eval_gettext '$APPLICATION_TITLE Application Configurator')"
sleep 2
if [ "$1" = "--prefix" ]
then
	shift
	export WINEPREFIX="$POL_USER_ROOT/wineprefix/$1"
else
	export WINEPREFIX="$(detect_wineprefix "$1")"
fi
shift
#[ "$WINEVERSION" = "" ] || POL_WINE$WINEVERSION
if [ "$1" = "wineserver" ]
then
        POL_Wine_AutoSetVersionEnv
	wineserver -k
else
	POL_Wine $@ &
fi
POL_SetupWindow_Close
exit
